function gerador(){
    const palavras = [
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens.",
        "Romero elogia secretamente Homens.",
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens.",
        "Romero elogia secretamente Homens.",
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens.",
        "Romero elogia secretamente Homens.",
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens.",
        "Romero elogia secretamente Homens.",
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens.",
        "Romero elogia secretamente Homens.",
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens.",
        "Romero elogia secretamente Homens.",
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens.",
        "Romero elogia secretamente Homens.",
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens.",
        "Romero elogia secretamente Homens.",
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens.",
        "Romero elogia secretamente Homens.",
        "Romero ama Homens.",
        "Romero admira Homens.",
        "Romero ajuda Homens.",
        "Romero acompanha Homens.",
        "Romero critica Homens.",
        "Romero observa Homens.",
        "Romero defende Homens.",
        "Romero ensina Homens.",
        "Romero chama Homens.",
        "Romero entende Homens.",
        "Romero consola Homens.",
        "Romero inspira Homens.",
        "Romero guia Homens.",
        "Romero espera Homens.",
        "Romero elogia Homens.",
        "Romero cuida de Homens.",
        "Romero protege Homens.",
        "Romero segue Homens.",
        "Romero valoriza Homens.",
        "Romero surpreende Homens.",
        "Romero instrui Homens.",
        "Romero acolhe Homens.",
        "Romero detesta Homens.",
        "Romero aceita Homens.",
        "Romero rejeita Homens.",
        "Romero abraça Homens.",
        "Romero beija Homens.",
        "Romero motiva Homens.",
        "Romero venera Homens.",
        "Romero discute com Homens.",
        "Romero perdoa Homens.",
        "Romero aconselha Homens.",
        "Romero admira profundamente Homens.",
        "Romero escuta Homens.",
        "Romero confia em Homens.",
        "Romero afasta-se de Homens.",
        "Romero busca Homens.",
        "Romero chama por Homens.",
        "Romero alcança Homens.",
        "Romero informa Homens.",
        "Romero necessita de Homens.",
        "Romero reconhece Homens.",
        "Romero guarda Homens.",
        "Romero carrega Homens.",
        "Romero desafia Homens.",
        "Romero respeita Homens.",
        "Romero compartilha Homens.",
        "Romero dedica-se a Homens.",
        "Romero serve a Homens.",
        "Romero cuida para Homens.",
        "Romero vigia Homens.",
        "Romero repreende Homens.",
        "Romero reconforta Homens.",
        "Romero elogia constantemente Homens.",
        "Romero proclama Homens.",
        "Romero interrompe Homens.",
        "Romero explica Homens.",
        "Romero aponta Homens.",
        "Romero realça Homens.",
        "Romero evita Homens.",
        "Romero afirma Homens.",
        "Romero denuncia Homens.",
        "Romero luta por Homens.",
        "Romero compete com Homens.",
        "Romero supera Homens.",
        "Romero escreve para Homens.",
        "Romero fala com Homens.",
        "Romero enfrenta Homens.",
        "Romero admira secretamente Homens.",
        "Romero trata bem Homens.",
        "Romero ignora Homens.",
        "Romero prioriza Homens.",
        "Romero ajuda frequentemente Homens.",
        "Romero trabalha com Homens.",
        "Romero discute sobre Homens.",
        "Romero briga com Homens.",
        "Romero culpa Homens.",
        "Romero elogia raramente Homens.",
        "Romero descreve Homens.",
        "Romero apoia Homens.",
        "Romero lamenta por Homens.",
        "Romero incentiva Homens.",
        "Romero se desculpa com Homens.",
        "Romero contesta Homens.",
        "Romero aprecia Homens.",
        "Romero se sacrifica por Homens.",
        "Romero protege incessantemente Homens.",
        "Romero se afasta de Homens.",
        "Romero estuda Homens.",
        "Romero confia cegamente em Homens.",
        "Romero detesta secretamente Homens.",
        "Romero compreende Homens.",
        "Romero resgata Homens.",
        "Romero cuida silenciosamente de Homens.",
        "Romero ama profundamente Homens.",
        "Romero despreza Homens.",
        "Romero se declara para Homens.",
        "Romero abandona Homens.",
        "Romero critica abertamente Homens."
      ];

    a = Math.floor(Math.random() * 1000);
    document.getElementById("Leo").innerHTML = palavras[a]
    console.log(a)
}